# Generated by Django 3.1 on 2020-11-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateField(auto_now=True),
        ),
    ]
