# Generated by Django 3.1 on 2020-11-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20201102_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='data_publicacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
