# Generated by Django 3.1 on 2020-11-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20201102_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
