# Generated by Django 3.1 on 2020-11-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacao',
            options={'ordering': ['-data_publicacao']},
        ),
    ]
