# Generated by Django 3.1 on 2020-09-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('usuario', models.CharField(max_length=20)),
                ('contatos', models.ManyToManyField(related_name='_perfis_contatos_+', to='perfis.Perfis')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('date_post', models.DateField()),
                ('comentarios', models.ManyToManyField(to='perfis.Comment')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfis')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25)),
                ('senha', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('perfis', models.ManyToManyField(to='perfis.Perfis')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfis')),
                ('postagens', models.ManyToManyField(to='perfis.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_react', models.CharField(choices=[('1', 'curtir'), ('2', 'amar'), ('3', 'rir'), ('4', 'imprecionar'), ('5', 'triste'), ('6', 'raiva')], max_length=1)),
                ('data', models.DateField()),
                ('peso', models.DecimalField(decimal_places=0, max_digits=4)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfis')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='reaction',
            field=models.ManyToManyField(to='perfis.Reaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfis'),
        ),
    ]
