# Generated by Django 3.1 on 2020-09-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('nome_empresa', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebidos', to='perfis.perfil')),
                ('solicitados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitados', to='perfis.perfil')),
            ],
        ),
    ]
