# Generated by Django 3.1 on 2020-11-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0006_publicacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacao',
        ),
    ]
